version: '3.4'

services:
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
  movieapi:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Movies.API/Dockerfile
